#!/usr/bin/env sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r ${HOME}/.Xresources ] && xrdb ${HOME}/.Xresources
vncconfig -iconic &
xsetroot -solid grey
dbus-launch --exit-with-session gnome-session &
